[pytest]
minversion = 7.0
pythonpath = .
testpaths = app/test
asyncio_mode = auto

# Marcadores
markers =
    asyncio: Tests asíncronos

# Ignorar warnings de Pydantic (deuda técnica)
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20